spring:
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.gmail.com
    port: 587 #Gmail SMTP 서버 포트
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          writetimeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    redis:
      host: 3.34.179.232  # Redis 서버의 호스트 주소를 설정
      port: 6379       # Redis 서버가 수신 대기하는 포트를 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_ENDPOINT}:13306/subs_db?serverTimezone=Asia/Seoul&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true  # data.sql 실행 시점 조정
  sql:
    init:
      mode: naver #naver는 sql파일을 실행하지 않는다 -> 실행 필요할경우 -> always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
springdoc:
  default-flat-param-object: true
  use-fqn: true
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    try-it-out-enabled: true
mail:
  address:
    admin: ${ADMIN_EMAIL}
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 600
  refresh-token-expiration-minutes: 4200
file:
  upload-dir: s3://subs-upload-files/
  default-image: /noImage.png
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_BUCKET_NAME}
    stack:
      auto: false
